### ISSUE TITLE
[frontend] to-do

### ISSUE THREAD

**Issue by eesum** [welovecherry/ft_transcendence#8]
- [x] https 연결 설정
- [x] 언어 설정 기능 추가
- [x] test api 용으로 주입해둔 정보 정리하기
- [x] OAuth login 여부 확인해서 라우팅하도록 변경
- [x] setting 없이 game 접근 방지 처리
- [x] .env 분리
- [x] 없는주소를 칠 경우?
